version: '3.8'
services:
  localstack: 
    image: localstack/localstack:latest
    environment: 
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sqs,lambda,logs,iam
      - DEBUG=1
    ports: 
      - '4566:4566'